var _apiHash = GoogleHash.generate();

var _mSiteName = 'Google Maps';var _mZoomIn = 'Zoom In';var _mZoomOut = 'Zoom Out';var _mZoomSet = 'Click to set zoom level';var _mZoomDrag = 'Drag to zoom';var _mPanWest = 'Go left';var _mPanEast = 'Go right';var _mPanNorth = 'Go up';var _mPanSouth = 'Go down';var _mLastResult = 'Return to the last result';var _mGoogleCopy = '©2005 Google';var _mDataCopy = 'Map data ©2005 ';var _mNavteq = 'NAVTEQ\u2122';var _mTeleAtlas = 'Tele Atlas';var _mZenrin = 'ZENRIN';var _mZenrinCopy = 'Map ©2005 ';var _mNormalMap = 'Map';var _mNormalMapShort = 'Map';var _mHybridMap = 'Hybrid';var _mHybridMapShort = 'Hyb';var _mNew = 'New!';var _mTerms = 'Terms of Use';var _mKeyholeMap = 'Satellite';var _mKeyholeMapShort = 'Sat';var _mKeyholeCopy = 'Imagery ©2005 ';var _mScale = 'Scale at the center of the map';var _mKilometers = 'km';var _mMiles = 'mi';var _mMeters = 'm';var _mFeet = 'ft';var _mDecimalPoint = '.';var _mThousandsSeparator = ',';var _mTermsURL = 'http://www.google.com/help/terms_local.html';

//var _apiHash = 'cbbe98f7cab3289826850d81785f4f9493937ea6';

//var _apiHash = '103b72bd9607ca94e74aa80cb107de9727df403b';
//prompt("",window.location.href);

var _apiKey = '';var _mApiBadKey = 'The Google Maps API key used on this web site was registered for a different web site. You can generate a new key for this web site at http://www.google.com/apis/maps/.';function createMapSpecs() {var mt = '';var tv = 'w2.5';var hmt = '';var htv = 'w2t.1';var kmt = '';var kdomain = 'google.com';var ktv = '3';var kdisable = false;var khauth = 'fzwq1B3JB15jcJNV0dNMOtuZGRw6w1gVoC7jIw';var mercator = (tv.charAt(0) == 'w');var kjapandatumhack = true;var keyholeMercator = 3 >= 3;var hybrid = (htv != '');if (!arguments.callee.mapSpecs) {var mapSpecs = [];if (mercator) {_GOOGLE_MAP_TYPE = new _GoogleMapMercSpec(mt, tv);} else {_GOOGLE_MAP_TYPE = new _GoogleMapSpec(mt, tv);}mapSpecs.push(_GOOGLE_MAP_TYPE);if (!kdisable) {if (keyholeMercator) {_SATELLITE_TYPE =new _KeyholeMapMercSpec(kmt, kdomain, ktv, khauth, kjapandatumhack);if (hybrid) {_HYBRID_TYPE =new _HybridMapSpec(kmt, kdomain, ktv, khauth, kjapandatumhack,hmt, htv);}} else {_SATELLITE_TYPE = new _KeyholeMapSpec(kmt, kdomain, ktv, mercator,khauth, kjapandatumhack);}mapSpecs.push(_SATELLITE_TYPE);if (_HYBRID_TYPE) {mapSpecs.push(_HYBRID_TYPE);}}arguments.callee.mapSpecs = mapSpecs;}return arguments.callee.mapSpecs;}var _u = navigator.userAgent.toLowerCase();function _ua(t) {return _u.indexOf(t) != -1;}function _uan(t){if(!window.RegExp){return 0;}var r = new RegExp(t+'([0-9]*)');var s = r.exec(_u);var ret = 0;if (s.length >= 2){ret = s[1];}return ret;}function _noActiveX(){if(!_ua('msie') || !document.all || _ua('opera')){return false;}var s = false;eval('try { new ActiveXObject("Microsoft.XMLDOM"); }'+'catch (e) { s = true; }');return s;}function _compat(){return ((_ua('opera') &&(_ua('opera 7.5') || _ua('opera/7.5') ||_ua('opera 8') || _ua('opera/8'))) ||(_ua('safari') && _uan('safari/') >= 125) ||(_ua('msie') &&!_ua('msie 4') && !_ua('msie 5.0') && !_ua('msie 5.1') &&!_ua('msie 3') && !_ua('powerpc')) ||(document.getElementById && window.XSLTProcessor &&window.XMLHttpRequest && !_ua('netscape6') &&!_ua('netscape/7.0')));}_fc = false;_c = _fc || _compat();function _browserIsCompatible(){return _c;}function GBrowserIsCompatible(){return _c;}function _havexslt(){if (typeof GetObject != 'undefined' ||(typeof XMLHttpRequest != 'undefined' &&typeof DOMParser != 'undefined' &&typeof XSLTProcessor != 'undefined')) {return true;} else {return false;}}function _script(src) {var ret='<'+'script src="'+src+'"'+' type="text/javascript"><'+'/script>';document.write(ret);}function _loadMapsScript(){if(_havexslt()){_script("http://maps.csail.mit.edu/library/static/GoogleMaps/maps.16.js");}else if(_ua('safari')){_script("http://maps.csail.mit.edu/library/static/GoogleMaps/maps.16.safari.js");}else{_script("http://maps.csail.mit.edu/library/static/GoogleMaps/maps.16.xslt.js");}}if (_c && !_noActiveX()) {document.write('');document.write('');_loadMapsScript();}